version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: classifier-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: classifiersdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appusersecret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "appuser", "--password=appusersecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  classifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classifier-service
    environment:
      - GO_ENV=production
      - SERVER_ADDR=:4000
      - DB_DSN=appuser:appusersecret@tcp(mysql:3306)/classifiersdb
      - DB_MAX_OPEN_CONNS=25
      - DB_MAX_IDLE_CONNS=25
      - DB_MAX_IDLE_TIME=15m
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: ["./wait-for-mysql.sh", "mysql", "./classifier"]
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: